language: go

go:
  - 1.13.6

jobs:
  include:
    - stage: test
      name: "Test"
      script: $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
      before_script:
        - go get golang.org/x/tools/cmd/cover
        - go get github.com/mattn/goveralls
        - go test -v -covermode=count -coverprofile=coverage.out
